services:
  - type: web
    name: coollibri-chatbot-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: mistral
      - key: DB_PROVIDER
        value: coollibri
